### ISSUE TITLE
bugged entity textures on some items in forgotten castle

### ISSUE THREAD

**Issue by itchyrock** [Karmabound/spellbound-modpack#1]
![image](https://github.com/Karmabound/spellbound-modpack/assets/149175590/8f50d528-cbe1-4024-ab93-ff341a1007d3)
![image](https://github.com/Karmabound/spellbound-modpack/assets/149175590/5bfd8afc-107f-4ce3-b7bb-5dc01f16ccff)
sentry's wrath and scarlet dagger both spawn with broken textures, uhh pls fix ok thanks

**Comment by Karmabound** [comment]
very pixelated image, did you notice this happening with any other Incendium-related mobs?

**Comment by Karmabound** [comment]
this will be fixed in alpha-2
