### ISSUE TITLE
Launching the game still gives a warning screen for RAM

### ISSUE THREAD

**Issue by Nekoneks** [Karmabound/spellbound-modpack#2]
Yeah, you said 4096MB was ok, and supposedly this was fixed, but I just booted it (alpha-2) up and it still gives the "Not enough RAM" warning.
<img width="422" alt="Screenshot 2023-11-04 at 7 16 02 PM" src="https://github.com/Karmabound/spellbound-modpack/assets/47909141/2d633ffa-23a4-4571-a123-6f3bde02b65e">

**Comment by Karmabound** [comment]
There seems to be either an issue with importing configs on your side, the memorysettings config is completely fine.
